#!/usr/bin/env bash
#
# Script for enabling/disabling system proxies
#
# -*- mode: shell-script -*-
#
set -e

# networksetup -listallnetworkservices
SERVICES=(
    'USB 10/100/1000 LAN'
    'Wi-Fi'
)

for i in ${!SERVICES[@]}
do
    SERVICE="${SERVICES[$i]}"
    (echo -n "Checking service ${SERVICE} ... "
     networksetup -listallnetworkservices | grep "${SERVICE}" >/dev/null && echo ok || echo fail) >&2
done

types=(
    ftp
    web
    secureweb
    streaming
    gopher
    socksfirewall
)

set_proxies() {
    for name in ${types[@]}
    do
        for i in ${!SERVICES[@]}
        do
            SERVICE="${SERVICES[$i]}"
            (set -x ; networksetup -set${name}proxystate "${SERVICE}" ${2})
        done
    done
}

get_proxies_status() {
    (for name in ${types[@]}
     do
         for i in ${!SERVICES[@]}
         do
             SERVICE="${SERVICES[$i]}"
             (set -x ; networksetup -get${name}proxy "${SERVICE}") | grep -E '^Enabled: '
         done
     done | sort -u)
}

case "$*" in
    on)
        set_proxies set On
        ;;
    off)
        set_proxies set Off
        ;;
    switch)
        case "$(get_proxies_status)" in
            "Enabled: No")
                set_proxies set On
                ;;
            "Enabled: Yes")
                set_proxies set Off
                ;;
            *)
                echo "Current status is mixed" >&2
                exit 2
        esac
        ;;
    status)
        get_proxies_status
        ;;
    *)
        echo 'Specify "on" or "off" argument' >&2
        exit 1
        ;;
esac

echo "done" >&2
