#!/usr/bin/env bash
#
# Script for enabling/disabling system proxies
#
# -*- mode: shell-script -*-
#
set -e

# networksetup -listallnetworkservices
SERVICE="${NETWORK_SERVICE:-USB 10/100/1000 LAN}"

(echo -n "Checking service ${SERVICE} ... "
 networksetup -listallnetworkservices | grep "${SERVICE}" >/dev/null && echo ok || echo fail) >&2

types=$(cat <<EOF
            ftp
            web
            secureweb
            streaming
            gopher
            socksfirewall
EOF
     )

set_proxies() {
    for name in $types
    do
        (set -x ; networksetup -set${name}proxystate "${SERVICE}" ${2})
    done
}

get_proxies_status() {
    (
     for name in $types
    do
        (set -x ; networksetup -get${name}proxy "${SERVICE}") | grep -E '^Enabled: '
    done | sort -u)
}

case "$*" in
    on)
        set_proxies set On
        ;;
    off)
        set_proxies set Off
        ;;
    switch)
        case "$(get_proxies_status)" in
            "Enabled: No")
                set_proxies set On
                ;;
            "Enabled: Yes")
                set_proxies set Off
                ;;
            *)
                echo "Current status is mixed" >&2
                exit 2
        esac
        ;;
    status)
        get_proxies_status
        ;;
    *)
        echo 'Specify "on" or "off" argument' >&2
        exit 1
        ;;
esac

echo "done" >&2
